import * as React from 'react';
/** Every glyph in the kit's Icon/Normal family. */
export type IconName =
  | "agent"
  | "ai-review"
  | "align-justify"
  | "arrow-left"
  | "arrow-left-thick"
  | "arrow-right"
  | "arrow-right-thick"
  | "arrow-turn-down"
  | "bell"
  | "bell-fill"
  | "blank"
  | "bookmark"
  | "bookmark-fill"
  | "bubble-plus"
  | "bubble-plus-fill"
  | "business-bag"
  | "business-bag-fill"
  | "calendar"
  | "calendar-person"
  | "camera"
  | "camera-fill"
  | "caret-down"
  | "caret-up"
  | "chat"
  | "check"
  | "check-thick"
  | "chevron-down"
  | "chevron-down-small"
  | "chevron-down-thick"
  | "chevron-down-thick-small"
  | "chevron-left"
  | "chevron-left-small"
  | "chevron-left-thick"
  | "chevron-left-thick-small"
  | "chevron-left-tight"
  | "chevron-left-tight-small"
  | "chevron-left-tight-thick"
  | "chevron-left-tight-thick-small"
  | "chevron-right"
  | "chevron-right-small"
  | "chevron-right-thick"
  | "chevron-right-thick-small"
  | "chevron-right-tight"
  | "chevron-right-tight-small"
  | "chevron-right-tight-thick"
  | "chevron-right-tight-thick-small"
  | "chevron-up"
  | "chevron-up-small"
  | "chevron-up-thick"
  | "chevron-up-thick-small"
  | "circle-check"
  | "circle-check-fill"
  | "circle-close"
  | "circle-close-fill"
  | "circle-exclamation"
  | "circle-exclamation-fill"
  | "circle-up-right"
  | "circle-up-right-fill"
  | "clock"
  | "clock-fill"
  | "close"
  | "close-thick"
  | "coffee"
  | "coffee-fill"
  | "column"
  | "company"
  | "company-fill"
  | "desktop"
  | "desktop-fill"
  | "document"
  | "document-fill"
  | "document-text"
  | "document-text-fill"
  | "dot"
  | "expand"
  | "collapse"
  | "external-link"
  | "flip-backward"
  | "graduation"
  | "graduation-fill"
  | "history"
  | "home"
  | "home-fill"
  | "image"
  | "inbox"
  | "left-side"
  | "line-horizontal"
  | "line-horizontal-thick"
  | "link"
  | "list-category"
  | "logout"
  | "mail"
  | "message"
  | "message-fill"
  | "minus"
  | "minus-thick"
  | "more-vertical"
  | "more-vertical-tight"
  | "pencil"
  | "pencil-fill"
  | "person"
  | "person-fill"
  | "persons"
  | "persons-fill"
  | "play"
  | "play-fill"
  | "plus"
  | "plus-thick"
  | "reset"
  | "search"
  | "search-thick"
  | "send"
  | "send-fill"
  | "setting"
  | "square-check"
  | "star"
  | "star-fill"
  | "trash"
  | "tune"
  | "write";
/**
 * Icon from the kit's own glyph set. Line geometry on a 24px grid, painted with
 * currentColor (stroke-width 1.5 by default).
 */
export interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  /** px. The file draws icons at 12 / 16 / 18 / 20 / 24. */
  size?: number | string;
  /** Stroke weight. 1.5 default; the *-thick names render +0.5. */
  strokeWidth?: number;
}
export declare const Icon: React.FC<IconProps> & { names: IconName[] };
export default Icon;
