"""note + content + algorithm

Revision ID: 4bb19e623718
Revises: ef0d5a7dd7da
Create Date: 2026-08-24 20:52:08.889278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bb19e623718'
down_revision: Union[str, Sequence[str], None] = 'ef0d5a7dd7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('difficulty', sa.String(length=8), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_platform', sa.String(length=32), nullable=False),
    sa.Column('source_number', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('curated_in', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('today', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('detail_path', sa.String(length=255), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_algorithm_published', 'algorithm', [sa.literal_column('published_on DESC')], unique=False)
    op.create_index('uq_algorithm_today', 'algorithm', ['today'], unique=True, postgresql_where=sa.text('today'))
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detail_path', sa.String(length=255), nullable=False),
    sa.Column('youtube_id', sa.String(length=16), nullable=False),
    sa.Column('duration', sa.String(length=16), nullable=True),
    sa.Column('speaker', sa.String(length=64), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_content_published', 'content', [sa.literal_column('published_on DESC')], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detail_path', sa.String(length=255), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_note_published', 'note', [sa.literal_column('published_on DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_note_published', table_name='note')
    op.drop_table('note')
    op.drop_index('ix_content_published', table_name='content')
    op.drop_table('content')
    op.drop_index('uq_algorithm_today', table_name='algorithm', postgresql_where=sa.text('today'))
    op.drop_index('ix_algorithm_published', table_name='algorithm')
    op.drop_table('algorithm')
    # ### end Alembic commands ###
